kubectl delete -f kibana/kibana-service.yaml
kubectl delete -f kibana/kibana.yaml
kubectl delete -f kibana/kibana-configMap.yaml
kubectl delete -f es-client/es-client-service.yaml
kubectl delete -f es-client/es-client.yaml
kubectl delete -f es-data/es-data.yaml
kubectl delete -f es-master/es-master.yaml
kubectl delete -f es-configs/es-configMap.yaml
kubectl delete -f es-namespace/namespace.yaml
